<?php

namespace Cibum\ConcursoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cibum\ConcursoBundle\Entity\Proyecto;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
   public function forProject(Proyecto $project)
   {
       return $this->getEntityManager()->createQuery('SELECT c FROM CibumConcursoBundle:Comment c WHERE c.project = :pj')
           ->setParameter('pj', $project)
           ->getResult();
   }
}