<?php

namespace Cibum\ConcursoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistritoRepository extends EntityRepository
{
}