<?php

namespace Cibum\ConcursoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoRepository extends EntityRepository
{

    public function findNew(array $list)
    {
        return $this->_em->createQuery('SELECT p FROM CibumConcursoBundle:Proyecto WHERE p.id IN :list')
            ->setParameter('list', $list)
            ->getResult();
    }
}